
server:
  port : 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone
    username: root
    password: lava
    driver-class-name: com.mysql.cj.jdbc.Driver

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
    show-sql: true

  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


